# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/damenly/workspace/Monoco

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/damenly/workspace/Monoco

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/damenly/workspace/Monoco/CMakeFiles /Users/damenly/workspace/Monoco/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/damenly/workspace/Monoco/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slave

# Build rule for target.
slave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slave
.PHONY : slave

# fast build rule for target.
slave/fast:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/build
.PHONY : slave/fast

#=============================================================================
# Target rules for targets named sentry

# Build rule for target.
sentry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sentry
.PHONY : sentry

# fast build rule for target.
sentry/fast:
	$(MAKE) -f CMakeFiles/sentry.dir/build.make CMakeFiles/sentry.dir/build
.PHONY : sentry/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/client.o: src/client.cpp.o

.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sentry.o: src/sentry.cpp.o

.PHONY : src/sentry.o

# target to build an object file
src/sentry.cpp.o:
	$(MAKE) -f CMakeFiles/sentry.dir/build.make CMakeFiles/sentry.dir/src/sentry.cpp.o
.PHONY : src/sentry.cpp.o

src/sentry.i: src/sentry.cpp.i

.PHONY : src/sentry.i

# target to preprocess a source file
src/sentry.cpp.i:
	$(MAKE) -f CMakeFiles/sentry.dir/build.make CMakeFiles/sentry.dir/src/sentry.cpp.i
.PHONY : src/sentry.cpp.i

src/sentry.s: src/sentry.cpp.s

.PHONY : src/sentry.s

# target to generate assembly for a file
src/sentry.cpp.s:
	$(MAKE) -f CMakeFiles/sentry.dir/build.make CMakeFiles/sentry.dir/src/sentry.cpp.s
.PHONY : src/sentry.cpp.s

src/slave.o: src/slave.cpp.o

.PHONY : src/slave.o

# target to build an object file
src/slave.cpp.o:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/src/slave.cpp.o
.PHONY : src/slave.cpp.o

src/slave.i: src/slave.cpp.i

.PHONY : src/slave.i

# target to preprocess a source file
src/slave.cpp.i:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/src/slave.cpp.i
.PHONY : src/slave.cpp.i

src/slave.s: src/slave.cpp.s

.PHONY : src/slave.s

# target to generate assembly for a file
src/slave.cpp.s:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/src/slave.cpp.s
.PHONY : src/slave.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... slave"
	@echo "... sentry"
	@echo "... client"
	@echo "... server"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sentry.o"
	@echo "... src/sentry.i"
	@echo "... src/sentry.s"
	@echo "... src/slave.o"
	@echo "... src/slave.i"
	@echo "... src/slave.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

